### ISSUE TITLE
Automapper issue

### ISSUE THREAD

**Issue by thedon-chris** [evgomes/supermarket-api#2]
`Startup.cs(36,22): error CS1061: 'IServiceCollection' does not contain a definition for 'AddAutoMapper' and no accessible extension method 'AddAutoMapper' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) `

Resolved by placing `using Automapper;` at the top of Startup.cs file

See https://stackoverflow.com/questions/42916182/trying-to-add-automapper-to-netcore1-1-not-recognising-services-addautomapper

**Comment by evgomes** [comment]
Hi @thedon-chris,

I couldn't simulate the problem. Which version of .NET Core do you have installed on your machine?

Please, try running `dotnet --version` and check if you have version 2.2 or above installed. 

If you have the correct version installed, please, try manually restoring dependencies accessing the folder `/src/Supermarket.API/` and running `dotnet restore`.

Let me know if it works, please.

**Comment by evgomes** [comment]
Hi,

I'll close the issue for now since I couldn't simulate it. If the problems happen again, please, reopen it.

Thank you.

**Comment by eric-wilson** [comment]
@subhanisyed17 - I had the same problem until I added AutoMapper.Extensions.Microsoft.DependencyInjection Nuget package.

https://www.nuget.org/packages/AutoMapper.Extensions.Microsoft.DependencyInjection/

**Comment by eskebab** [comment]
@eric-wilson thanks a lot. that did it for me as well!

**Comment by life-traveler** [comment]
@eric-wilson thank you

**Comment by evgomes** [comment]
@all-contributors please add @thedon-chris for bug
@all-contributors please add @subhanisyed17 for bug
@all-contributors please add @eric-wilson for question

**Comment by evgomes** [comment]
@all-contributors please add @thedon-chris for bug

**Comment by evgomes** [comment]
@all-contributors please add @subhanisyed17 for bug

**Comment by evgomes** [comment]
@all-contributors please add @eric-wilson for question

**Comment by Sunboy005** [comment]
If you are having issue with adding your auto mapper, It is better you check through the type and version you added.
If it is not  "AutoMapper.Extensions.Microsoft.DependencyInjection", then you won't be able to use "services.AddAutoMapper()".
Sometimes, you might mistakenly add "AutoMapper

**Comment by fmjnax** [comment]
> If you are having issue with adding your auto mapper, It is better you check through the type and version you added. If it is not "AutoMapper.Extensions.Microsoft.DependencyInjection", then you won't be able to use "services.AddAutoMapper()". Sometimes, you might mistakenly add "AutoMapper

@Sunboy005  Thanks!
This was the trick for me in my Blazor WASM project. I had both AutoMapper and AutoMapper.Extensions.Microsoft.DependencyInjection. I removed the AutoMapper package and everything worked.
