### ISSUE TITLE
Error adding AddAutoMapper in Startup.cs

### ISSUE THREAD

**Issue by mickyinba** [evgomes/supermarket-api#8]
I get error trying to add AutoMapper to my Startup.cs file in a dotNET Core project (a simple tutorial):

1. installed package from VS Code terminal:
dotnet add package AutoMapper
(this added:
  <PackageReference Include="AutoMapper" Version="10.0.0" /> 
to my .csproj file).
2. Added line inside ConfigureServices method:
 services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());
3. added "using" namespace in my Startup.cs file:
 using AutoMapper;

The error I get is:
'IServiceCollection' does not contain a definition for 'AddAutoMapper' and no accessible extension method 'AddAutoMapper' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

dotnet --version
= 3.1.402

What am I missing, please?

**Comment by mickyinba** [comment]
Ok, it seems package "AutoMapper.Extensions.Microsoft.DependencyInjection" is required as well and I didn't realize it.

Running next command fixes the issue:
dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection

**Comment by evgomes** [comment]
@all-contributors please add @miki-nis for bug
