### ISSUE TITLE
UnitOfWork not saving data in my db 

### ISSUE THREAD

**Issue by nunomarques97** [evgomes/supermarket-api#9]
Hello!!

I made an api using your tutorial
i can post objects into the database. However when i restart the app I loose all data. I follow ur pattern of UnitOfWork. Not sure if my EFCore version matters but im using 3.1.8 and Im using netcore 3.1. Also, i made the base project in netcore 2.2 like u did and then migrate to 3.1. any ideas what could be with the migration from 2.2 to 3.1?

**Comment by evgomes** [comment]
Hi @nunomarques97 

Which database are you using? Which database provider are you using with Entity Core?
I used an in-memory provider for this tutorial, so all data is kept in memory. Once you restart the API, all data is lost.

Here is an example of how to configure Entity Framework to store data into SQL Server, so data is not lost after API restarts: https://entityframeworkcore.com/knowledge-base/54460412/how-to-connect-configure-entity-framework-to-connect-to-sql-server-

Can you confirm which provider you are using? If you're already using a different database provider, please, share a bit of your code, this way I can check what is happening.

Thanks.

**Comment by nunomarques97** [comment]
this is my .csproj package:
`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.8" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Omnia.Fx.NetCore" Version="5.1.20" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc5" />
    
  </ItemGroup>

</Project>
`


does it help?

I also use like u did an in memory provider:

`services.AddDbContext<AppDbContext>(options =>
            {
                options.UseInMemoryDatabase(Configuration.GetConnectionString("memory"));
            });`

and i addopt ur Unitofwork pattern. if try to save it manually by SaveChangesAssyng it doesnt work as well

**Comment by nunomarques97** [comment]
![image](https://user-images.githubusercontent.com/75090036/102829631-7420b280-43df-11eb-9a74-57123df8d458.png)

here i my .csproject package does it help? i also use in memory provider

**Comment by evgomes** [comment]
Hi @nunomarques97 

Sorry for the late reply.

It seems you have installed the SQL Server provider, but you are still using the In-Memory provider to persist data.
Try changing the `AddDbContext` directive in the `Startup` class like this:

```
services.AddDbContext<YourDbContextClass>(opt =>
{
	opt.UseSqlServer("your_connection_string_here");
});
```

You can find more information on how to configure Entity to use SQL Server and how to add the connection string here: [https://docs.microsoft.com/pt-br/ef/core/dbcontext-configuration/](https://docs.microsoft.com/pt-br/ef/core/dbcontext-configuration/)

Let me know if it works.

**Comment by evgomes** [comment]
Hi,

I'll close this due to inactivity. If there are problems yet, please, let me know.

Thank you.
